// ============================================================
// VivyRTC — Firestore Signaling Module
// ============================================================
//
// Firebase Firestore is used ONLY to exchange the small pieces
// of metadata two browsers need to establish a direct WebRTC
// connection: the SDP offer, the SDP answer, ICE candidates,
// and call status. No audio/video ever touches Firestore.
//
// Firestore structure:
//
//   calls/{callId}
//     callerId:   string   — random client-generated id of the caller
//     receiverId: string|null — random client-generated id of the receiver
//     status:     string   — "waiting" | "connected" | "ended"
//     offer:      { type, sdp } | null
//     answer:     { type, sdp } | null
//     createdAt:  server timestamp
//     updatedAt:  server timestamp
//
//   calls/{callId}/callerCandidates/{autoId}
//     — ICE candidates generated by the caller (JSON from candidate.toJSON())
//
//   calls/{callId}/receiverCandidates/{autoId}
//     — ICE candidates generated by the receiver (JSON from candidate.toJSON())
// ============================================================

import {
  doc,
  setDoc,
  getDoc,
  updateDoc,
  onSnapshot,
  collection,
  addDoc,
  getDocs,
  deleteDoc,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js";

import { db } from "./firebase.js";

/** Generates a short random client id used to tag caller/receiver. */
export function generateLocalId() {
  return "user-" + Math.random().toString(36).slice(2, 10);
}

/**
 * Deletes every document in a subcollection. Used to clear out
 * leftover ICE candidates from a previous test session before a
 * Call ID is reused, so stale candidates don't get fed into a
 * brand-new connection.
 */
async function clearSubcollection(callId, subcollectionName) {
  const colRef = collection(db, "calls", callId, subcollectionName);
  const snap = await getDocs(colRef);
  await Promise.all(snap.docs.map((docSnap) => deleteDoc(docSnap.ref)));
}

/**
 * Creates a new call document with the given SDP offer, after
 * clearing any leftover candidates from a previous use of the
 * same Call ID.
 *
 * @param {string} callId
 * @param {RTCSessionDescriptionInit} offer
 * @param {string} callerId
 */
export async function createCall(callId, offer, callerId) {
  if (!callId) {
    throw new Error("Please enter a Call ID.");
  }

  try {
    await clearSubcollection(callId, "callerCandidates");
    await clearSubcollection(callId, "receiverCandidates");

    const callRef = doc(db, "calls", callId);
    await setDoc(callRef, {
      callerId,
      receiverId: null,
      status: "waiting",
      offer: { type: offer.type, sdp: offer.sdp },
      answer: null,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    });

    return callRef;
  } catch (err) {
    console.error("[VivyRTC] createCall error:", err);
    throw new Error("Could not create the call. Check your internet connection and Firebase configuration.");
  }
}

/**
 * Retrieves the SDP offer for an existing call. Throws a friendly
 * error if the call doesn't exist, has no offer, or has already ended.
 *
 * @param {string} callId
 * @returns {Promise<RTCSessionDescriptionInit>}
 */
export async function getCallOffer(callId) {
  if (!callId) {
    throw new Error("Please enter a Call ID.");
  }

  let snap;
  try {
    snap = await getDoc(doc(db, "calls", callId));
  } catch (err) {
    console.error("[VivyRTC] getCallOffer error:", err);
    throw new Error("Could not reach the signaling server. Check your internet connection.");
  }

  if (!snap.exists()) {
    throw new Error("Call ID not found. Double-check the Call ID and make sure the other person created the call first.");
  }

  const data = snap.data();

  if (data.status === "ended") {
    throw new Error("This call has already ended. Ask the other person to create a new call.");
  }

  if (!data.offer || !data.offer.sdp || !data.offer.type) {
    throw new Error("This call's offer data is missing or invalid.");
  }

  return data.offer;
}

/**
 * Writes the SDP answer to an existing call document and marks
 * the call as connected.
 *
 * @param {string} callId
 * @param {RTCSessionDescriptionInit} answer
 * @param {string} receiverId
 */
export async function setAnswer(callId, answer, receiverId) {
  try {
    const callRef = doc(db, "calls", callId);
    await updateDoc(callRef, {
      receiverId,
      answer: { type: answer.type, sdp: answer.sdp },
      status: "connected",
      updatedAt: serverTimestamp()
    });
  } catch (err) {
    console.error("[VivyRTC] setAnswer error:", err);
    throw new Error("Could not send the answer. Check your internet connection.");
  }
}

/**
 * Listens for the SDP answer being added to a call document (caller
 * side). Calls `callback(answer)` exactly once, the first time an
 * answer appears. Returns an unsubscribe function.
 *
 * @param {string} callId
 * @param {(answer: RTCSessionDescriptionInit) => void} callback
 * @returns {() => void} unsubscribe
 */
export function listenForAnswer(callId, callback) {
  const callRef = doc(db, "calls", callId);

  return onSnapshot(
    callRef,
    (snap) => {
      if (!snap.exists()) return;
      const data = snap.data();
      if (data.answer && data.answer.sdp && data.answer.type) {
        callback(data.answer);
      }
    },
    (err) => {
      console.error("[VivyRTC] listenForAnswer error:", err);
    }
  );
}

/**
 * Listens for status changes on a call document (e.g. the other
 * side ending the call). Returns an unsubscribe function.
 *
 * @param {string} callId
 * @param {(status: string) => void} callback
 * @returns {() => void} unsubscribe
 */
export function listenForCallStatus(callId, callback) {
  const callRef = doc(db, "calls", callId);

  return onSnapshot(
    callRef,
    (snap) => {
      if (!snap.exists()) return;
      const data = snap.data();
      if (data.status) {
        callback(data.status);
      }
    },
    (err) => {
      console.error("[VivyRTC] listenForCallStatus error:", err);
    }
  );
}

/** Adds a caller-side ICE candidate to Firestore. */
export async function addCallerCandidate(callId, candidate) {
  try {
    await addDoc(collection(db, "calls", callId, "callerCandidates"), candidate.toJSON());
  } catch (err) {
    console.error("[VivyRTC] addCallerCandidate error:", err);
  }
}

/** Adds a receiver-side ICE candidate to Firestore. */
export async function addReceiverCandidate(callId, candidate) {
  try {
    await addDoc(collection(db, "calls", callId, "receiverCandidates"), candidate.toJSON());
  } catch (err) {
    console.error("[VivyRTC] addReceiverCandidate error:", err);
  }
}

/**
 * Listens for new caller-side ICE candidates (receiver side listens
 * to this). Calls `callback(candidateInit)` for every candidate added
 * from this point forward. Returns an unsubscribe function.
 */
export function listenForCallerCandidates(callId, callback) {
  const colRef = collection(db, "calls", callId, "callerCandidates");

  return onSnapshot(
    colRef,
    (snap) => {
      snap.docChanges().forEach((change) => {
        if (change.type === "added") {
          callback(change.doc.data());
        }
      });
    },
    (err) => {
      console.error("[VivyRTC] listenForCallerCandidates error:", err);
    }
  );
}

/**
 * Listens for new receiver-side ICE candidates (caller side listens
 * to this). Calls `callback(candidateInit)` for every candidate added
 * from this point forward. Returns an unsubscribe function.
 */
export function listenForReceiverCandidates(callId, callback) {
  const colRef = collection(db, "calls", callId, "receiverCandidates");

  return onSnapshot(
    colRef,
    (snap) => {
      snap.docChanges().forEach((change) => {
        if (change.type === "added") {
          callback(change.doc.data());
        }
      });
    },
    (err) => {
      console.error("[VivyRTC] listenForReceiverCandidates error:", err);
    }
  );
}

/**
 * Marks a call document as ended. Safe to call even if the document
 * no longer exists or the network is briefly unavailable — errors
 * are logged but not thrown, since this is typically called during
 * cleanup where we don't want to block the UI.
 */
export async function updateCallStatus(callId, status) {
  try {
    const callRef = doc(db, "calls", callId);
    await updateDoc(callRef, {
      status,
      updatedAt: serverTimestamp()
    });
  } catch (err) {
    console.error("[VivyRTC] updateCallStatus error:", err);
  }
}
